apiVersion: v1
kind: Service
metadata:
  name: {{ include "openclaw.fullname" . }}
  labels:
    {{- include "openclaw.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.gateway.port }}
      targetPort: gateway
      protocol: TCP
      name: gateway
    - port: {{ .Values.gateway.bridgePort }}
      targetPort: bridge
      protocol: TCP
      name: bridge
  selector:
    {{- include "openclaw.selectorLabels" . | nindent 4 }}
